
#=====================================================
label BS_Chg_A_UntPos03_01:
#=====================================================
#-------------------------------
    call BS_Update_A_S3_UntStorePOS
    call BS_Update_A_S1_UntStorePOS
#-------------------------------
    $ A_S3_Ctl_Type = A_S1_UntStorePOS [0]
    $ A_S3_Reg_No = A_S1_UntStorePOS [1]
    $ A_S3_Name = A_S1_UntStorePOS [2]
    $ A_S3_Level = A_S1_UntStorePOS [3]
    $ A_S3_Exp = A_S1_UntStorePOS [4]
    $ A_S3_MHP = A_S1_UntStorePOS [5]
    $ A_S3_HP = A_S1_UntStorePOS [6]
    $ A_S3_Atk = A_S1_UntStorePOS [7]
    $ A_S3_Mag = A_S1_UntStorePOS [8]
    $ A_S3_Def = A_S1_UntStorePOS [9]
    $ A_S3_Res = A_S1_UntStorePOS [10]
    $ A_S3_Spd = A_S1_UntStorePOS [11] 
    $ A_S3_Cls = A_S1_UntStorePOS [12]
    $ A_S3_Ttc = A_S1_UntStorePOS [13]
    $ A_S3_Ocu = A_S1_UntStorePOS [14]
    $ A_S3_CanAct = A_S1_UntStorePOS [15]
    $ A_S3_Mor = A_S1_UntStorePOS [16]
    $ A_S3_Fgt = A_S1_UntStorePOS [17]
    $ A_S3_Stn = A_S1_UntStorePOS [18]
    $ A_S3_AtkType = A_S1_UntStorePOS [19]
    $ A_S3_DefType = A_S1_UntStorePOS [20]
    $ A_S3_CrtChc = A_S1_UntStorePOS [21]
    $ A_S3_EvdChc = A_S1_UntStorePOS [22]
    $ A_S3_DuelChc = A_S1_UntStorePOS [23]
    $ A_S3_DuelEvd = A_S1_UntStorePOS [24]
    $ A_S3_AtkIcr = A_S1_UntStorePOS [25]
    $ A_S3_AtkDcr = A_S1_UntStorePOS [26]
    $ A_S3_AtkChg = A_S1_UntStorePOS [27]
    $ A_S3_DefIcr = A_S1_UntStorePOS [28]
    $ A_S3_DefDcr = A_S1_UntStorePOS [29]
    $ A_S3_DefChg = A_S1_UntStorePOS [30]
    $ A_S3_MorIcr = A_S1_UntStorePOS [31]
    $ A_S3_MorDcr = A_S1_UntStorePOS [32]
    $ A_S3_MorChg = A_S1_UntStorePOS [33]
    $ A_S3_Kill = A_S1_UntStorePOS [34]
    $ A_S3_Killed = A_S1_UntStorePOS [35]
    $ A_S3_ChgTtc_Count = A_S1_UntStorePOS [36]
    $ A_S3_ChgPos_Count = A_S1_UntStorePOS [37]
#-------------------------------
#-------------------------------
    $ A_S1_Ctl_Type = A_S3_UntStorePOS [0]
    $ A_S1_Reg_No = A_S3_UntStorePOS [1]
    $ A_S1_Name = A_S3_UntStorePOS [2]
    $ A_S1_Level = A_S3_UntStorePOS [3]
    $ A_S1_Exp = A_S3_UntStorePOS [4]
    $ A_S1_MHP = A_S3_UntStorePOS [5]
    $ A_S1_HP = A_S3_UntStorePOS [6]
    $ A_S1_Atk = A_S3_UntStorePOS [7]
    $ A_S1_Mag = A_S3_UntStorePOS [8]
    $ A_S1_Def = A_S3_UntStorePOS [9]
    $ A_S1_Res = A_S3_UntStorePOS [10]
    $ A_S1_Spd = A_S3_UntStorePOS [11] 
    $ A_S1_Cls = A_S3_UntStorePOS [12]
    $ A_S1_Ttc = A_S3_UntStorePOS [13]
    $ A_S1_Ocu = A_S3_UntStorePOS [14]
    $ A_S1_CanAct = A_S3_UntStorePOS [15]
    $ A_S1_Mor = A_S3_UntStorePOS [16]
    $ A_S1_Fgt = A_S3_UntStorePOS [17]
    $ A_S1_Stn = A_S3_UntStorePOS [18]
    $ A_S1_AtkType = A_S3_UntStorePOS [19]
    $ A_S1_DefType = A_S3_UntStorePOS [20]
    $ A_S1_CrtChc = A_S3_UntStorePOS [21]
    $ A_S1_EvdChc = A_S3_UntStorePOS [22]
    $ A_S1_DuelChc = A_S3_UntStorePOS [23]
    $ A_S1_DuelEvd = A_S3_UntStorePOS [24]
    $ A_S1_AtkIcr = A_S3_UntStorePOS [25]
    $ A_S1_AtkDcr = A_S3_UntStorePOS [26]
    $ A_S1_AtkChg = A_S3_UntStorePOS [27]
    $ A_S1_DefIcr = A_S3_UntStorePOS [28]
    $ A_S1_DefDcr = A_S3_UntStorePOS [29]
    $ A_S1_DefChg = A_S3_UntStorePOS [30]
    $ A_S1_MorIcr = A_S3_UntStorePOS [31]
    $ A_S1_MorDcr = A_S3_UntStorePOS [32]
    $ A_S1_MorChg = A_S3_UntStorePOS [33]
    $ A_S1_Kill = A_S3_UntStorePOS [34]
    $ A_S1_Killed = A_S3_UntStorePOS [35]
    $ A_S1_ChgTtc_Count = A_S3_UntStorePOS [36]
    $ A_S1_ChgPos_Count = A_S3_UntStorePOS [37]
#-------------------------------
    return

#=====================================================
label BS_Chg_A_UntPos03_02:
#=====================================================
#-------------------------------
    call BS_Update_A_S3_UntStorePOS
    call BS_Update_A_S2_UntStorePOS
#-------------------------------
    $ A_S3_Ctl_Type = A_S2_UntStorePOS [0]
    $ A_S3_Reg_No = A_S2_UntStorePOS [1]
    $ A_S3_Name = A_S2_UntStorePOS [2]
    $ A_S3_Level = A_S2_UntStorePOS [3]
    $ A_S3_Exp = A_S2_UntStorePOS [4]
    $ A_S3_MHP = A_S2_UntStorePOS [5]
    $ A_S3_HP = A_S2_UntStorePOS [6]
    $ A_S3_Atk = A_S2_UntStorePOS [7]
    $ A_S3_Mag = A_S2_UntStorePOS [8]
    $ A_S3_Def = A_S2_UntStorePOS [9]
    $ A_S3_Res = A_S2_UntStorePOS [10]
    $ A_S3_Spd = A_S2_UntStorePOS [11] 
    $ A_S3_Cls = A_S2_UntStorePOS [12]
    $ A_S3_Ttc = A_S2_UntStorePOS [13]
    $ A_S3_Ocu = A_S2_UntStorePOS [14]
    $ A_S3_CanAct = A_S2_UntStorePOS [15]
    $ A_S3_Mor = A_S2_UntStorePOS [16]
    $ A_S3_Fgt = A_S2_UntStorePOS [17]
    $ A_S3_Stn = A_S2_UntStorePOS [18]
    $ A_S3_AtkType = A_S2_UntStorePOS [19]
    $ A_S3_DefType = A_S2_UntStorePOS [20]
    $ A_S3_CrtChc = A_S2_UntStorePOS [21]
    $ A_S3_EvdChc = A_S2_UntStorePOS [22]
    $ A_S3_DuelChc = A_S2_UntStorePOS [23]
    $ A_S3_DuelEvd = A_S2_UntStorePOS [24]
    $ A_S3_AtkIcr = A_S2_UntStorePOS [25]
    $ A_S3_AtkDcr = A_S2_UntStorePOS [26]
    $ A_S3_AtkChg = A_S2_UntStorePOS [27]
    $ A_S3_DefIcr = A_S2_UntStorePOS [28]
    $ A_S3_DefDcr = A_S2_UntStorePOS [29]
    $ A_S3_DefChg = A_S2_UntStorePOS [30]
    $ A_S3_MorIcr = A_S2_UntStorePOS [31]
    $ A_S3_MorDcr = A_S2_UntStorePOS [32]
    $ A_S3_MorChg = A_S2_UntStorePOS [33]
    $ A_S3_Kill = A_S2_UntStorePOS [34]
    $ A_S3_Killed = A_S2_UntStorePOS [35]
    $ A_S3_ChgTtc_Count = A_S2_UntStorePOS [36]
    $ A_S3_ChgPos_Count = A_S2_UntStorePOS [37]
#-------------------------------
#-------------------------------
    $ A_S2_Ctl_Type = A_S3_UntStorePOS [0]
    $ A_S2_Reg_No = A_S3_UntStorePOS [1]
    $ A_S2_Name = A_S3_UntStorePOS [2]
    $ A_S2_Level = A_S3_UntStorePOS [3]
    $ A_S2_Exp = A_S3_UntStorePOS [4]
    $ A_S2_MHP = A_S3_UntStorePOS [5]
    $ A_S2_HP = A_S3_UntStorePOS [6]
    $ A_S2_Atk = A_S3_UntStorePOS [7]
    $ A_S2_Mag = A_S3_UntStorePOS [8]
    $ A_S2_Def = A_S3_UntStorePOS [9]
    $ A_S2_Res = A_S3_UntStorePOS [10]
    $ A_S2_Spd = A_S3_UntStorePOS [11] 
    $ A_S2_Cls = A_S3_UntStorePOS [12]
    $ A_S2_Ttc = A_S3_UntStorePOS [13]
    $ A_S2_Ocu = A_S3_UntStorePOS [14]
    $ A_S2_CanAct = A_S3_UntStorePOS [15]
    $ A_S2_Mor = A_S3_UntStorePOS [16]
    $ A_S2_Fgt = A_S3_UntStorePOS [17]
    $ A_S2_Stn = A_S3_UntStorePOS [18]
    $ A_S2_AtkType = A_S3_UntStorePOS [19]
    $ A_S2_DefType = A_S3_UntStorePOS [20]
    $ A_S2_CrtChc = A_S3_UntStorePOS [21]
    $ A_S2_EvdChc = A_S3_UntStorePOS [22]
    $ A_S2_DuelChc = A_S3_UntStorePOS [23]
    $ A_S2_DuelEvd = A_S3_UntStorePOS [24]
    $ A_S2_AtkIcr = A_S3_UntStorePOS [25]
    $ A_S2_AtkDcr = A_S3_UntStorePOS [26]
    $ A_S2_AtkChg = A_S3_UntStorePOS [27]
    $ A_S2_DefIcr = A_S3_UntStorePOS [28]
    $ A_S2_DefDcr = A_S3_UntStorePOS [29]
    $ A_S2_DefChg = A_S3_UntStorePOS [30]
    $ A_S2_MorIcr = A_S3_UntStorePOS [31]
    $ A_S2_MorDcr = A_S3_UntStorePOS [32]
    $ A_S2_MorChg = A_S3_UntStorePOS [33]
    $ A_S2_Kill = A_S3_UntStorePOS [34]
    $ A_S2_Killed = A_S3_UntStorePOS [35]
    $ A_S2_ChgTtc_Count = A_S3_UntStorePOS [36]
    $ A_S2_ChgPos_Count = A_S3_UntStorePOS [37]
#-------------------------------
    return

#=====================================================
label BS_Chg_A_UntPos03_04:
#=====================================================
#-------------------------------
    call BS_Update_A_S3_UntStorePOS
    call BS_Update_A_S4_UntStorePOS
#-------------------------------
    $ A_S3_Ctl_Type = A_S4_UntStorePOS [0]
    $ A_S3_Reg_No = A_S4_UntStorePOS [1]
    $ A_S3_Name = A_S4_UntStorePOS [2]
    $ A_S3_Level = A_S4_UntStorePOS [3]
    $ A_S3_Exp = A_S4_UntStorePOS [4]
    $ A_S3_MHP = A_S4_UntStorePOS [5]
    $ A_S3_HP = A_S4_UntStorePOS [6]
    $ A_S3_Atk = A_S4_UntStorePOS [7]
    $ A_S3_Mag = A_S4_UntStorePOS [8]
    $ A_S3_Def = A_S4_UntStorePOS [9]
    $ A_S3_Res = A_S4_UntStorePOS [10]
    $ A_S3_Spd = A_S4_UntStorePOS [11] 
    $ A_S3_Cls = A_S4_UntStorePOS [12]
    $ A_S3_Ttc = A_S4_UntStorePOS [13]
    $ A_S3_Ocu = A_S4_UntStorePOS [14]
    $ A_S3_CanAct = A_S4_UntStorePOS [15]
    $ A_S3_Mor = A_S4_UntStorePOS [16]
    $ A_S3_Fgt = A_S4_UntStorePOS [17]
    $ A_S3_Stn = A_S4_UntStorePOS [18]
    $ A_S3_AtkType = A_S4_UntStorePOS [19]
    $ A_S3_DefType = A_S4_UntStorePOS [20]
    $ A_S3_CrtChc = A_S4_UntStorePOS [21]
    $ A_S3_EvdChc = A_S4_UntStorePOS [22]
    $ A_S3_DuelChc = A_S4_UntStorePOS [23]
    $ A_S3_DuelEvd = A_S4_UntStorePOS [24]
    $ A_S3_AtkIcr = A_S4_UntStorePOS [25]
    $ A_S3_AtkDcr = A_S4_UntStorePOS [26]
    $ A_S3_AtkChg = A_S4_UntStorePOS [27]
    $ A_S3_DefIcr = A_S4_UntStorePOS [28]
    $ A_S3_DefDcr = A_S4_UntStorePOS [29]
    $ A_S3_DefChg = A_S4_UntStorePOS [30]
    $ A_S3_MorIcr = A_S4_UntStorePOS [31]
    $ A_S3_MorDcr = A_S4_UntStorePOS [32]
    $ A_S3_MorChg = A_S4_UntStorePOS [33]
    $ A_S3_Kill = A_S4_UntStorePOS [34]
    $ A_S3_Killed = A_S4_UntStorePOS [35]
    $ A_S3_ChgTtc_Count = A_S4_UntStorePOS [36]
    $ A_S3_ChgPos_Count = A_S4_UntStorePOS [37]
#-------------------------------
#-------------------------------
    $ A_S4_Ctl_Type = A_S3_UntStorePOS [0]
    $ A_S4_Reg_No = A_S3_UntStorePOS [1]
    $ A_S4_Name = A_S3_UntStorePOS [2]
    $ A_S4_Level = A_S3_UntStorePOS [3]
    $ A_S4_Exp = A_S3_UntStorePOS [4]
    $ A_S4_MHP = A_S3_UntStorePOS [5]
    $ A_S4_HP = A_S3_UntStorePOS [6]
    $ A_S4_Atk = A_S3_UntStorePOS [7]
    $ A_S4_Mag = A_S3_UntStorePOS [8]
    $ A_S4_Def = A_S3_UntStorePOS [9]
    $ A_S4_Res = A_S3_UntStorePOS [10]
    $ A_S4_Spd = A_S3_UntStorePOS [11] 
    $ A_S4_Cls = A_S3_UntStorePOS [12]
    $ A_S4_Ttc = A_S3_UntStorePOS [13]
    $ A_S4_Ocu = A_S3_UntStorePOS [14]
    $ A_S4_CanAct = A_S3_UntStorePOS [15]
    $ A_S4_Mor = A_S3_UntStorePOS [16]
    $ A_S4_Fgt = A_S3_UntStorePOS [17]
    $ A_S4_Stn = A_S3_UntStorePOS [18]
    $ A_S4_AtkType = A_S3_UntStorePOS [19]
    $ A_S4_DefType = A_S3_UntStorePOS [20]
    $ A_S4_CrtChc = A_S3_UntStorePOS [21]
    $ A_S4_EvdChc = A_S3_UntStorePOS [22]
    $ A_S4_DuelChc = A_S3_UntStorePOS [23]
    $ A_S4_DuelEvd = A_S3_UntStorePOS [24]
    $ A_S4_AtkIcr = A_S3_UntStorePOS [25]
    $ A_S4_AtkDcr = A_S3_UntStorePOS [26]
    $ A_S4_AtkChg = A_S3_UntStorePOS [27]
    $ A_S4_DefIcr = A_S3_UntStorePOS [28]
    $ A_S4_DefDcr = A_S3_UntStorePOS [29]
    $ A_S4_DefChg = A_S3_UntStorePOS [30]
    $ A_S4_MorIcr = A_S3_UntStorePOS [31]
    $ A_S4_MorDcr = A_S3_UntStorePOS [32]
    $ A_S4_MorChg = A_S3_UntStorePOS [33]
    $ A_S4_Kill = A_S3_UntStorePOS [34]
    $ A_S4_Killed = A_S3_UntStorePOS [35]
    $ A_S4_ChgTtc_Count = A_S3_UntStorePOS [36]
    $ A_S4_ChgPos_Count = A_S3_UntStorePOS [37]
#-------------------------------
    return

#=====================================================
label BS_Chg_A_UntPos03_05:
#=====================================================
#-------------------------------
    call BS_Update_A_S3_UntStorePOS
    call BS_Update_A_S5_UntStorePOS
#-------------------------------
    $ A_S3_Ctl_Type = A_S5_UntStorePOS [0]
    $ A_S3_Reg_No = A_S5_UntStorePOS [1]
    $ A_S3_Name = A_S5_UntStorePOS [2]
    $ A_S3_Level = A_S5_UntStorePOS [3]
    $ A_S3_Exp = A_S5_UntStorePOS [4]
    $ A_S3_MHP = A_S5_UntStorePOS [5]
    $ A_S3_HP = A_S5_UntStorePOS [6]
    $ A_S3_Atk = A_S5_UntStorePOS [7]
    $ A_S3_Mag = A_S5_UntStorePOS [8]
    $ A_S3_Def = A_S5_UntStorePOS [9]
    $ A_S3_Res = A_S5_UntStorePOS [10]
    $ A_S3_Spd = A_S5_UntStorePOS [11] 
    $ A_S3_Cls = A_S5_UntStorePOS [12]
    $ A_S3_Ttc = A_S5_UntStorePOS [13]
    $ A_S3_Ocu = A_S5_UntStorePOS [14]
    $ A_S3_CanAct = A_S5_UntStorePOS [15]
    $ A_S3_Mor = A_S5_UntStorePOS [16]
    $ A_S3_Fgt = A_S5_UntStorePOS [17]
    $ A_S3_Stn = A_S5_UntStorePOS [18]
    $ A_S3_AtkType = A_S5_UntStorePOS [19]
    $ A_S3_DefType = A_S5_UntStorePOS [20]
    $ A_S3_CrtChc = A_S5_UntStorePOS [21]
    $ A_S3_EvdChc = A_S5_UntStorePOS [22]
    $ A_S3_DuelChc = A_S5_UntStorePOS [23]
    $ A_S3_DuelEvd = A_S5_UntStorePOS [24]
    $ A_S3_AtkIcr = A_S5_UntStorePOS [25]
    $ A_S3_AtkDcr = A_S5_UntStorePOS [26]
    $ A_S3_AtkChg = A_S5_UntStorePOS [27]
    $ A_S3_DefIcr = A_S5_UntStorePOS [28]
    $ A_S3_DefDcr = A_S5_UntStorePOS [29]
    $ A_S3_DefChg = A_S5_UntStorePOS [30]
    $ A_S3_MorIcr = A_S5_UntStorePOS [31]
    $ A_S3_MorDcr = A_S5_UntStorePOS [32]
    $ A_S3_MorChg = A_S5_UntStorePOS [33]
    $ A_S3_Kill = A_S5_UntStorePOS [34]
    $ A_S3_Killed = A_S5_UntStorePOS [35]
    $ A_S3_ChgTtc_Count = A_S5_UntStorePOS [36]
    $ A_S3_ChgPos_Count = A_S5_UntStorePOS [37]
#-------------------------------
#-------------------------------
    $ A_S5_Ctl_Type = A_S3_UntStorePOS [0]
    $ A_S5_Reg_No = A_S3_UntStorePOS [1]
    $ A_S5_Name = A_S3_UntStorePOS [2]
    $ A_S5_Level = A_S3_UntStorePOS [3]
    $ A_S5_Exp = A_S3_UntStorePOS [4]
    $ A_S5_MHP = A_S3_UntStorePOS [5]
    $ A_S5_HP = A_S3_UntStorePOS [6]
    $ A_S5_Atk = A_S3_UntStorePOS [7]
    $ A_S5_Mag = A_S3_UntStorePOS [8]
    $ A_S5_Def = A_S3_UntStorePOS [9]
    $ A_S5_Res = A_S3_UntStorePOS [10]
    $ A_S5_Spd = A_S3_UntStorePOS [11] 
    $ A_S5_Cls = A_S3_UntStorePOS [12]
    $ A_S5_Ttc = A_S3_UntStorePOS [13]
    $ A_S5_Ocu = A_S3_UntStorePOS [14]
    $ A_S5_CanAct = A_S3_UntStorePOS [15]
    $ A_S5_Mor = A_S3_UntStorePOS [16]
    $ A_S5_Fgt = A_S3_UntStorePOS [17]
    $ A_S5_Stn = A_S3_UntStorePOS [18]
    $ A_S5_AtkType = A_S3_UntStorePOS [19]
    $ A_S5_DefType = A_S3_UntStorePOS [20]
    $ A_S5_CrtChc = A_S3_UntStorePOS [21]
    $ A_S5_EvdChc = A_S3_UntStorePOS [22]
    $ A_S5_DuelChc = A_S3_UntStorePOS [23]
    $ A_S5_DuelEvd = A_S3_UntStorePOS [24]
    $ A_S5_AtkIcr = A_S3_UntStorePOS [25]
    $ A_S5_AtkDcr = A_S3_UntStorePOS [26]
    $ A_S5_AtkChg = A_S3_UntStorePOS [27]
    $ A_S5_DefIcr = A_S3_UntStorePOS [28]
    $ A_S5_DefDcr = A_S3_UntStorePOS [29]
    $ A_S5_DefChg = A_S3_UntStorePOS [30]
    $ A_S5_MorIcr = A_S3_UntStorePOS [31]
    $ A_S5_MorDcr = A_S3_UntStorePOS [32]
    $ A_S5_MorChg = A_S3_UntStorePOS [33]
    $ A_S5_Kill = A_S3_UntStorePOS [34]
    $ A_S5_Killed = A_S3_UntStorePOS [35]
    $ A_S5_ChgTtc_Count = A_S3_UntStorePOS [36]
    $ A_S5_ChgPos_Count = A_S3_UntStorePOS [37]
#-------------------------------
    return

#=====================================================
label BS_Chg_A_UntPos03_06:
#=====================================================
#-------------------------------
    call BS_Update_A_S3_UntStorePOS
    call BS_Update_A_S6_UntStorePOS
#-------------------------------
    $ A_S3_Ctl_Type = A_S6_UntStorePOS [0]
    $ A_S3_Reg_No = A_S6_UntStorePOS [1]
    $ A_S3_Name = A_S6_UntStorePOS [2]
    $ A_S3_Level = A_S6_UntStorePOS [3]
    $ A_S3_Exp = A_S6_UntStorePOS [4]
    $ A_S3_MHP = A_S6_UntStorePOS [5]
    $ A_S3_HP = A_S6_UntStorePOS [6]
    $ A_S3_Atk = A_S6_UntStorePOS [7]
    $ A_S3_Mag = A_S6_UntStorePOS [8]
    $ A_S3_Def = A_S6_UntStorePOS [9]
    $ A_S3_Res = A_S6_UntStorePOS [10]
    $ A_S3_Spd = A_S6_UntStorePOS [11] 
    $ A_S3_Cls = A_S6_UntStorePOS [12]
    $ A_S3_Ttc = A_S6_UntStorePOS [13]
    $ A_S3_Ocu = A_S6_UntStorePOS [14]
    $ A_S3_CanAct = A_S6_UntStorePOS [15]
    $ A_S3_Mor = A_S6_UntStorePOS [16]
    $ A_S3_Fgt = A_S6_UntStorePOS [17]
    $ A_S3_Stn = A_S6_UntStorePOS [18]
    $ A_S3_AtkType = A_S6_UntStorePOS [19]
    $ A_S3_DefType = A_S6_UntStorePOS [20]
    $ A_S3_CrtChc = A_S6_UntStorePOS [21]
    $ A_S3_EvdChc = A_S6_UntStorePOS [22]
    $ A_S3_DuelChc = A_S6_UntStorePOS [23]
    $ A_S3_DuelEvd = A_S6_UntStorePOS [24]
    $ A_S3_AtkIcr = A_S6_UntStorePOS [25]
    $ A_S3_AtkDcr = A_S6_UntStorePOS [26]
    $ A_S3_AtkChg = A_S6_UntStorePOS [27]
    $ A_S3_DefIcr = A_S6_UntStorePOS [28]
    $ A_S3_DefDcr = A_S6_UntStorePOS [29]
    $ A_S3_DefChg = A_S6_UntStorePOS [30]
    $ A_S3_MorIcr = A_S6_UntStorePOS [31]
    $ A_S3_MorDcr = A_S6_UntStorePOS [32]
    $ A_S3_MorChg = A_S6_UntStorePOS [33]
    $ A_S3_Kill = A_S6_UntStorePOS [34]
    $ A_S3_Killed = A_S6_UntStorePOS [35]
    $ A_S3_ChgTtc_Count = A_S6_UntStorePOS [36]
    $ A_S3_ChgPos_Count = A_S6_UntStorePOS [37]
#-------------------------------
#-------------------------------
    $ A_S6_Ctl_Type = A_S3_UntStorePOS [0]
    $ A_S6_Reg_No = A_S3_UntStorePOS [1]
    $ A_S6_Name = A_S3_UntStorePOS [2]
    $ A_S6_Level = A_S3_UntStorePOS [3]
    $ A_S6_Exp = A_S3_UntStorePOS [4]
    $ A_S6_MHP = A_S3_UntStorePOS [5]
    $ A_S6_HP = A_S3_UntStorePOS [6]
    $ A_S6_Atk = A_S3_UntStorePOS [7]
    $ A_S6_Mag = A_S3_UntStorePOS [8]
    $ A_S6_Def = A_S3_UntStorePOS [9]
    $ A_S6_Res = A_S3_UntStorePOS [10]
    $ A_S6_Spd = A_S3_UntStorePOS [11] 
    $ A_S6_Cls = A_S3_UntStorePOS [12]
    $ A_S6_Ttc = A_S3_UntStorePOS [13]
    $ A_S6_Ocu = A_S3_UntStorePOS [14]
    $ A_S6_CanAct = A_S3_UntStorePOS [15]
    $ A_S6_Mor = A_S3_UntStorePOS [16]
    $ A_S6_Fgt = A_S3_UntStorePOS [17]
    $ A_S6_Stn = A_S3_UntStorePOS [18]
    $ A_S6_AtkType = A_S3_UntStorePOS [19]
    $ A_S6_DefType = A_S3_UntStorePOS [20]
    $ A_S6_CrtChc = A_S3_UntStorePOS [21]
    $ A_S6_EvdChc = A_S3_UntStorePOS [22]
    $ A_S6_DuelChc = A_S3_UntStorePOS [23]
    $ A_S6_DuelEvd = A_S3_UntStorePOS [24]
    $ A_S6_AtkIcr = A_S3_UntStorePOS [25]
    $ A_S6_AtkDcr = A_S3_UntStorePOS [26]
    $ A_S6_AtkChg = A_S3_UntStorePOS [27]
    $ A_S6_DefIcr = A_S3_UntStorePOS [28]
    $ A_S6_DefDcr = A_S3_UntStorePOS [29]
    $ A_S6_DefChg = A_S3_UntStorePOS [30]
    $ A_S6_MorIcr = A_S3_UntStorePOS [31]
    $ A_S6_MorDcr = A_S3_UntStorePOS [32]
    $ A_S6_MorChg = A_S3_UntStorePOS [33]
    $ A_S6_Kill = A_S3_UntStorePOS [34]
    $ A_S6_Killed = A_S3_UntStorePOS [35]
    $ A_S6_ChgTtc_Count = A_S3_UntStorePOS [36]
    $ A_S6_ChgPos_Count = A_S3_UntStorePOS [37]
#-------------------------------
    return
