screen Scr_Duel:
#///////////////////////  ATTACKER SLOT 1
    if DS_A_Type == "Solider":
        if DS_A_AntAct == "Died":
            add "A_Cls01_Idl" at DS_A_Eft_Cls_001_Die
        elif DS_A_AntAct == "Evade_Idle":
            add "A_Cls01_Evd_Idl" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Evade_Return":
            add "A_Cls01_Evd_Rtn" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Damged" and DS_A_CanEvd == 0:
            add "A_Cls01_Idl" at DS_A_Eft_Cls_001_Dmged
        elif DS_A_AntAct == "Idle":
            add "A_Cls01_Idl" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Ready":
            add "A_Cls01_Rdy" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Hit":
            if DS_A_DmgType == "Melee":
                add "A_Cls01_Atk_Melee" at DS_A_Eft_Cls_001
            elif DS_A_DmgType == "Range":
                add "A_Cls01_Atk_Range" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "CritHit":
            if DS_A_DmgType == "Melee":
                add "A_Cls01_Atk_Melee_Crit" at DS_A_Eft_Cls_001
            elif DS_A_DmgType == "Range":
                add "A_Cls01_Atk_Range_Crit" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Hit_Idle":
            if DS_A_DmgType == "Melee":
                add "A_Cls01_Atk_Melee_Idle" at DS_A_Eft_Cls_001
            elif DS_A_DmgType == "Range":
                add "A_Cls01_Atk_Range_Idle" at DS_A_Eft_Cls_001
        elif DS_A_AntAct == "Return":
            if DS_A_DmgType == "Melee":
                add "A_Cls01_Atk_Melee_Return" at DS_A_Eft_Cls_001
            elif DS_A_DmgType == "Range":
                add "A_Cls01_Atk_Range_Return" at DS_A_Eft_Cls_001
    elif DS_A_Type == "Archer":
        if DS_A_AntAct == "Died":
            add "A_Cls02_Idl" at DS_A_Eft_Cls_002_Die
        elif DS_A_AntAct == "Evade_Idle":
            add "A_Cls02_Evd_Idl" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Evade_Return":
            add "A_Cls02_Evd_Rtn" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Damged" and DS_A_CanEvd == 0:
            add "A_Cls02_Idl" at DS_A_Eft_Cls_002_Dmged
        elif DS_A_AntAct == "Idle":
            add "A_Cls02_Idl" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Ready":
            add "A_Cls02_Rdy" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Hit":
            if DS_A_DmgType == "Melee":
                add "A_Cls02_Atk_Melee" at DS_A_Eft_Cls_002
            elif DS_A_DmgType == "Range":
                add "A_Cls02_Atk_Range" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "CritHit":
            if DS_A_DmgType == "Melee":
                add "A_Cls02_Atk_Melee_Crit" at DS_A_Eft_Cls_002
            elif DS_A_DmgType == "Range":
                add "A_Cls02_Atk_Range_Crit" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Hit_Idle":
            if DS_A_DmgType == "Melee":
                add "A_Cls02_Atk_Melee_Idle" at DS_A_Eft_Cls_002
            elif DS_A_DmgType == "Range":
                add "A_Cls02_Atk_Range_Idle" at DS_A_Eft_Cls_002
        elif DS_A_AntAct == "Return":
            if DS_A_DmgType == "Melee":
                add "A_Cls02_Atk_Melee_Return" at DS_A_Eft_Cls_002
            elif DS_A_DmgType == "Range":
                add "A_Cls02_Atk_Range_Return" at DS_A_Eft_Cls_002
    elif DS_A_Type == "Horse_Rider":
        if DS_A_AntAct == "Died":
            add "A_Cls03_Idl" at DS_A_Eft_Cls_003_Die
        elif DS_A_AntAct == "Evade_Idle":
            add "A_Cls03_Evd_Idl" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Evade_Return":
            add "A_Cls03_Evd_Rtn" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Damged" and DS_A_CanEvd == 0:
            add "A_Cls03_Idl" at DS_A_Eft_Cls_003_Dmged
        elif DS_A_AntAct == "Idle":
            add "A_Cls03_Idl" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Ready":
            add "A_Cls03_Rdy" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Hit":
            if DS_A_DmgType == "Melee":
                add "A_Cls03_Atk_Melee" at DS_A_Eft_Cls_003
            elif DS_A_DmgType == "Range":
                add "A_Cls03_Atk_Range" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "CritHit":
            if DS_A_DmgType == "Melee":
                add "A_Cls03_Atk_Melee_Crit" at DS_A_Eft_Cls_003
            elif DS_A_DmgType == "Range":
                add "A_Cls03_Atk_Range_Crit" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Hit_Idle":
            if DS_A_DmgType == "Melee":
                add "A_Cls03_Atk_Melee_Idle" at DS_A_Eft_Cls_003
            elif DS_A_DmgType == "Range":
                add "A_Cls03_Atk_Range_Idle" at DS_A_Eft_Cls_003
        elif DS_A_AntAct == "Return":
            if DS_A_DmgType == "Melee":
                add "A_Cls03_Atk_Melee_Return" at DS_A_Eft_Cls_003
            elif DS_A_DmgType == "Range":
                add "A_Cls03_Atk_Range_Return" at DS_A_Eft_Cls_003
    elif DS_A_Type == "Healer":
        if DS_A_AntAct == "Died":
            add "A_Cls04_Idl" at DS_A_Eft_Cls_004_Die
        elif DS_A_AntAct == "Evade_Idle":
            add "A_Cls04_Evd_Idl" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Evade_Return":
            add "A_Cls04_Evd_Rtn" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Damged" and DS_A_CanEvd == 0:
            add "A_Cls04_Idl" at DS_A_Eft_Cls_004_Dmged
        elif DS_A_AntAct == "Idle":
            add "A_Cls04_Idl" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Ready":
            add "A_Cls04_Rdy" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Hit":
            if DS_A_DmgType == "Melee":
                add "A_Cls04_Atk_Melee" at DS_A_Eft_Cls_004
            elif DS_A_DmgType == "Range":
                add "A_Cls04_Atk_Range" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "CritHit":
            if DS_A_DmgType == "Melee":
                add "A_Cls04_Atk_Melee_Crit" at DS_A_Eft_Cls_004
            elif DS_A_DmgType == "Range":
                add "A_Cls04_Atk_Range_Crit" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Hit_Idle":
            if DS_A_DmgType == "Melee":
                add "A_Cls04_Atk_Melee_Idle" at DS_A_Eft_Cls_004
            elif DS_A_DmgType == "Range":
                add "A_Cls04_Atk_Range_Idle" at DS_A_Eft_Cls_004
        elif DS_A_AntAct == "Return":
            if DS_A_DmgType == "Melee":
                add "A_Cls04_Atk_Melee_Return" at DS_A_Eft_Cls_004
            elif DS_A_DmgType == "Range":
                add "A_Cls04_Atk_Range_Return" at DS_A_Eft_Cls_004






                    
                    
                    

#///////////////////////  DEFFENDER SLOT 1
    if DS_D_Type == "Solider":
        if DS_D_AntAct == "Died":
            add "D_Cls01_Idl" at DS_D_Eft_Cls_001_Die
        elif DS_D_AntAct == "Evade_Idle":
            add "D_Cls01_Evd_Idl" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Evade_Return":
            add "D_Cls01_Evd_Rtn" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Damged" and DS_D_CanEvd == 0:
            add "D_Cls01_Idl" at DS_D_Eft_Cls_001_Dmged
        elif DS_D_AntAct == "Idle":
            add "D_Cls01_Idl" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Ready":
            add "D_Cls01_Rdy" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Hit":
            if DS_D_DmgType == "Melee":
                add "D_Cls01_Atk_Melee" at DS_D_Eft_Cls_001
            elif DS_D_DmgType == "Range":
                add "D_Cls01_Atk_Range" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "CritHit":
            if DS_D_DmgType == "Melee":
                add "D_Cls01_Atk_Melee_Crit" at DS_D_Eft_Cls_001
            elif DS_D_DmgType == "Range":
                add "D_Cls01_Atk_Range_Crit" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Hit_Idle":
            if DS_D_DmgType == "Melee":
                add "D_Cls01_Atk_Melee_Idle" at DS_D_Eft_Cls_001
            elif DS_D_DmgType == "Range":
                add "D_Cls01_Atk_Range_Idle" at DS_D_Eft_Cls_001
        elif DS_D_AntAct == "Return":
            if DS_D_DmgType == "Melee":
                add "D_Cls01_Atk_Melee_Return" at DS_D_Eft_Cls_001
            elif DS_D_DmgType == "Range":
                add "D_Cls01_Atk_Range_Return" at DS_D_Eft_Cls_001
    elif DS_D_Type == "Archer":
        if DS_D_AntAct == "Died":
            add "D_Cls02_Idl" at DS_D_Eft_Cls_002_Die
        elif DS_D_AntAct == "Evade_Idle":
            add "D_Cls02_Evd_Idl" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Evade_Return":
            add "D_Cls02_Evd_Rtn" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Damged" and DS_D_CanEvd == 0:
            add "D_Cls02_Idl" at DS_D_Eft_Cls_002_Dmged
        elif DS_D_AntAct == "Idle":
            add "D_Cls02_Idl" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Ready":
            add "D_Cls02_Rdy" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Hit":
            if DS_D_DmgType == "Melee":
                add "D_Cls02_Atk_Melee" at DS_D_Eft_Cls_002
            elif DS_D_DmgType == "Range":
                add "D_Cls02_Atk_Range" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "CritHit":
            if DS_D_DmgType == "Melee":
                add "D_Cls02_Atk_Melee_Crit" at DS_D_Eft_Cls_002
            elif DS_D_DmgType == "Range":
                add "D_Cls02_Atk_Range_Crit" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Hit_Idle":
            if DS_D_DmgType == "Melee":
                add "D_Cls02_Atk_Melee_Idle" at DS_D_Eft_Cls_002
            elif DS_D_DmgType == "Range":
                add "D_Cls02_Atk_Range_Idle" at DS_D_Eft_Cls_002
        elif DS_D_AntAct == "Return":
            if DS_D_DmgType == "Melee":
                add "D_Cls02_Atk_Melee_Return" at DS_D_Eft_Cls_002
            elif DS_D_DmgType == "Range":
                add "D_Cls02_Atk_Range_Return" at DS_D_Eft_Cls_002
    elif DS_D_Type == "Horse_Rider":
        if DS_D_AntAct == "Died":
            add "D_Cls03_Idl" at DS_D_Eft_Cls_003_Die
        elif DS_D_AntAct == "Evade_Idle":
            add "D_Cls03_Evd_Idl" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Evade_Return":
            add "D_Cls03_Evd_Rtn" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Damged" and DS_D_CanEvd == 0:
            add "D_Cls03_Idl" at DS_D_Eft_Cls_003_Dmged
        elif DS_D_AntAct == "Idle":
            add "D_Cls03_Idl" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Ready":
            add "D_Cls03_Rdy" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Hit":
            if DS_D_DmgType == "Melee":
                add "D_Cls03_Atk_Melee" at DS_D_Eft_Cls_003
            elif DS_D_DmgType == "Range":
                add "D_Cls03_Atk_Range" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "CritHit":
            if DS_D_DmgType == "Melee":
                add "D_Cls03_Atk_Melee_Crit" at DS_D_Eft_Cls_003
            elif DS_D_DmgType == "Range":
                add "D_Cls03_Atk_Range_Crit" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Hit_Idle":
            if DS_D_DmgType == "Melee":
                add "D_Cls03_Atk_Melee_Idle" at DS_D_Eft_Cls_003
            elif DS_D_DmgType == "Range":
                add "D_Cls03_Atk_Range_Idle" at DS_D_Eft_Cls_003
        elif DS_D_AntAct == "Return":
            if DS_D_DmgType == "Melee":
                add "D_Cls03_Atk_Melee_Return" at DS_D_Eft_Cls_003
            elif DS_D_DmgType == "Range":
                add "D_Cls03_Atk_Range_Return" at DS_D_Eft_Cls_003
    elif DS_D_Type == "Healer":
        if DS_D_AntAct == "Died":
            add "D_Cls04_Idl" at DS_D_Eft_Cls_004_Die
        elif DS_D_AntAct == "Evade_Idle":
            add "D_Cls04_Evd_Idl" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Evade_Return":
            add "D_Cls04_Evd_Rtn" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Damged" and DS_D_CanEvd == 0:
            add "D_Cls04_Idl" at DS_D_Eft_Cls_004_Dmged
        elif DS_D_AntAct == "Idle":
            add "D_Cls04_Idl" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Ready":
            add "D_Cls04_Rdy" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Hit":
            if DS_D_DmgType == "Melee":
                add "D_Cls04_Atk_Melee" at DS_D_Eft_Cls_004
            elif DS_D_DmgType == "Range":
                add "D_Cls04_Atk_Range" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "CritHit":
            if DS_D_DmgType == "Melee":
                add "D_Cls04_Atk_Melee_Crit" at DS_D_Eft_Cls_004
            elif DS_D_DmgType == "Range":
                add "D_Cls04_Atk_Range_Crit" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Hit_Idle":
            if DS_D_DmgType == "Melee":
                add "D_Cls04_Atk_Melee_Idle" at DS_D_Eft_Cls_004
            elif DS_D_DmgType == "Range":
                add "D_Cls04_Atk_Range_Idle" at DS_D_Eft_Cls_004
        elif DS_D_AntAct == "Return":
            if DS_D_DmgType == "Melee":
                add "D_Cls04_Atk_Melee_Return" at DS_D_Eft_Cls_004
            elif DS_D_DmgType == "Range":
                add "D_Cls04_Atk_Range_Return" at DS_D_Eft_Cls_004
