init: 
    image SMM_tittle    = "Images/SMM/Theme/SMM_Title.png"
    image SMM_Screen_title  = "Images/SMM/Theme/SMM_Mainmenu.png"

    image BG_000 = "Images/SMM/Background/BG - 000.jpg"
    image BG_001 = "Images/SMM/Background/BG - 001.jpg"
    image BG_002 = "Images/SMM/Background/BG - 002.jpg"
    image BG_003 = "Images/SMM/Background/BG - 003.jpg"
    image BG_004 = "Images/SMM/Background/BG - 004.jpg"
    image BG_005 = "Images/SMM/Background/BG - 005.jpg"
    image BG_006 = "Images/SMM/Background/BG - 006.jpg"
    image BG_007 = "Images/SMM/Background/BG - 007.jpg"
    image BG_008 = "Images/SMM/Background/BG - 008.jpg"
    image BG_009 = "Images/SMM/Background/BG - 009.jpg"
    image BG_010 = "Images/SMM/Background/BG - 010.jpg"
    image BG_011 = "Images/SMM/Background/BG - 011.jpg"
    image BG_012 = "Images/SMM/Background/BG - 012.jpg"
    image BG_013 = "Images/SMM/Background/BG - 013.jpg"
    image BG_014 = "Images/SMM/Background/BG - 014.jpg"
    image BG_015 = "Images/SMM/Background/BG - 015.jpg"
    image BG_016 = "Images/SMM/Background/BG - 016.jpg"